prodserver:
      build: .

blackbox-test:
  build: blackbox-test
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - .:/opt/project
  working_dir: /opt/project/blackbox-test
  links:
    - prodserver
  entrypoint: ["/opt/project/blackbox-test/bin/start.sh"]